apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-vars
  namespace: comfy
data:
  #########The next 2 vars are for the cert management
  namespace: "comfy"
  clusterfqdn: "comfy.gucasassi.com"
  admin_email: "gucasassi@gmail.com"
